// database/reviews.tsx

export interface Review {
  id: string;
  name: string;
  rating: number;
  comment: string;
  date: string;
}

const NAMES = [
  // Male Names (Common)
  "Ali Raza", "Usman Ahmed", "Hamza Malik", "Bilal Hussain", "Omar Shah", 
  "Hassan Iqbal", "Fahad Ali", "Danish Ahmed", "Kashif Riaz", "Farhan Malik", 
  "Rizwan Ullah", "Adnan Khan", "Zohaib Hassan", "Waqar Ahmed", "Ahsan Khan",
  "Saad Qureshi", "Yasir Shah", "Ahad Raza", "Fawad Ali", "Asim Khan", 
  "Zain Ul Abidin", "Arslan Naseer", "Taha Ahmed", "Mohsin Ali", "Amir Khan",
  "Salman Saqib", "Junaid Khan", "Shahzad Ahmed", "Adeel Chaudhry", "Sohaib Khan",
  "Haris Ali", "Faizan Sheikh", "Shoaib Ahmed", "Kamran Khan", "Zeeshan Haider",
  "Waseem Abbas", "Nasir Khan", "Imran Farooq", "Kaleem Ullah", "Obaid Khan",
  "Raheel Ahmed", "Tahir Shah", "Umair Khan", "Bilal Ashraf", "Noman Ijaz",
  
  // Female Names (Common)
  "Sara Khan", "Zainab Fatima", "Ayesha Bibi", "Fatima Noor", "Sana Tariq", 
  "Hina Khan", "Mariam Bibi", "Nida Ahmed", "Sadia Khan", "Amna Sheikh", 
  "Mehwish Gul", "Rabia Basri", "Javeria Abbasi", "Kinza Malik", "Iqra Noor", 
  "Sajal Khan", "Mahira Ahmed", "Momina Khan", "Hania Ali", "Kubra Malik",
  "Zara Ahmed", "Kiran Shah", "Saira Yousaf", "Bushra Bibi", "Asma Khan",
  "Farheen Iqbal", "Anum Fayyaz", "Tehreem Khan", "Laiba Khan", "Mahnoor Ali",
  "Bisma Khan", "Urwa Ahmed", "Mawra Ali", "Yumna Khan", "Saboor Malik",
  "Sidra Amin", "Naila Khan", "Sania Ahmed", "Beenish Raja", "Momal Sheikh"
];

const COMMENTS = [
  "Bhot hi zabardast khushbu hai!",
  "Long lasting and premium feel.",
  "Value for money, totally recommended.",
  "Packaging was amazing, and the scent is divine.",
  "Mujhe yeh gift mein mila aur mujhe pyar ho gaya is se.",
  "Thora strong hai shuru mein, lekin dry down bhot acha hai.",
  "Best perfume I have bought online in Pakistan.",
  "Delivery fast thi aur product authentic hai.",
  "Nice projection, lasts about 8-10 hours on clothes.",
  "Will definitely buy again.",
  "Fragrance thori sweet hai, mujhe pasand aayi.",
  "Bilkul original brand jaisi vibes aati hain.",
  "Office wear ke liye perfect hai.",
  "Raat ki parties ke liye best choice.",
  "Mehngay brands se behtar quality hai.",
  "Amazing scent, highly recommended!",
  "Khushbu bhot achi hai, lekin delivery thori late hui.",
  "Totally satisfied with the purchase.",
  "Bottle ki quality aur packing bhot luxurious hai.",
  "Mera naya favorite perfume ban gaya hai.",
  "Scent bhot unique hai, sab puchte hain konsa lagaya hai.",
  "Gift dene ke liye perfect option hai.",
  "Price ke hisaab se quality bhot achi hai.",
  "Mujhe woody notes bhot pasand aaye.",
  "Fresh aur energetic feel deta hai.",
  "Garmiyon ke liye best perfume hai.",
  "Sardiyon mein iski projection aur bhi achi hoti hai.",
  "Bohat hi classy fragrance hai.",
  "Har koi tareef karta hai jab main yeh lagata hoon.",
  "Lasting kamal ki hai, subah lagaya shaam tak khushbu thi.",
  "Original brands ko takkar deta hai yeh.",
  "Packaging dekh kar hi dil khush ho gaya.",
  "Fast delivery aur cooperative staff.",
  "Maza aa gaya use kar ke.",
  "Zabardast! Will order more soon.",
  "Thora sa mehenga hai lekin worth it hai.",
  "Khushbu bhot soft aur decent hai.",
  "Sar dard nahi hota is se, bhot pleasant hai.",
  "Daily use ke liye acha hai.",
  "Special occasions par lagane ke liye rakha hai.",
  "Blind buy kiya tha, lekin regret nahi hua.",
  "Review parh kar liya tha, waqai acha nikla.",
  "Bottle bhot khoobsurat hai.",
  "Mera teesra order hai, quality maintain rakhi hai.",
  "Highly addictive smell!",
  "Bhai wah! Kya cheez bana di hai.",
  "Mujhe floral notes pasand hain, aur yeh perfect hai.",
  "Oud ki khushbu bhot balanced hai.",
  "Citrus freshness bhot achi hai.",
  "Musk ka touch bhot royal lagta hai.",
  "Excellent customer service.",
  "Jaisi description thi, waisa hi nikla.",
  "Thora aur discount hota to acha tha.",
  "Free tester bhi mila, bhot acha laga.",
  "Packing itni achi thi ke kholne ka dil nahi kar raha tha.",
  "Scent trail bhot achi chorta hai.",
  "Kapron pe dhoone ke baad bhi khushbu aa rahi thi.",
  "Bhot romantic fragrance hai.",
  "Father ke liye liya tha, unhein bhot pasand aaya.",
  "Mother's day gift ke liye best hai.",
  "Husband ko gift kiya, wo bhot khush hue.",
  "Wife ko bhot pasand aaya.",
  "Unisex hai, main aur meri begum dono use karte hain.",
  "Signature scent ban gaya hai mera.",
  "University ke liye acha hai.",
  "Gym ke baad lagata hoon, fresh feel hota hai.",
  "Travel size bhi hona chahiye.",
  "Bara bottle launch karein please.",
  "Sample pack order kiya tha, ab full bottle lunga.",
  "Khushbu bhot sophisticated hai.",
  "Cheap perfumes jaisi smell nahi hai.",
  "Lagta hai koi mehnga designer perfume lagaya hai.",
  "Projection could be better, but smell is 10/10.",
  "Lasting is okay, 5-6 hours.",
  "8 hours plus lasting hai easy.",
  "Kapron par 2 din tak rehti hai khushbu.",
  "Skin friendly hai, koi irritation nahi hui.",
  "Spray nozzle bhot acha hai.",
  "Cap thora loose tha, lekin perfume acha hai.",
  "Leakage ka issue tha, lekin replace kar diya.",
  "Customer support bhot helpful hai.",
  "Rider bhot tameez wala tha.",
  "Lahore mein 2 din mein mil gaya.",
  "Karachi ki garmi mein bhi tikta hai.",
  "Islamabad ke mausam ke liye best hai.",
  "Multan ki garmi mein bhi projection achi hai.",
  "Peshawar delivery bhot fast thi.",
  "Quetta mein bhi deliver ho gaya, thanks.",
  "Poora ghar mehak utha.",
  "Gaari mein rakhne ke liye acha hai.",
  "Pocket perfume bhi launch karein.",
  "Oil based lagta hai, quality achi hai.",
  "Alcohol ki smell nahi aati shuru mein.",
  "Notes ki blending bhot achi hai.",
  "Top notes thore sharp hain, middle notes best hain.",
  "Base notes bhot creamy aur smooth hain.",
  "Vanilla ka touch bhot acha hai.",
  "Rose ki khushbu bhot natural hai.",
  "Sandalwood note is prominent.",
  "Amber lovers ke liye treat hai.",
  "Tobacco note bhot masculine hai.",
  "Leather accord bhot rich hai.",
  "Fruity notes bhot juicy lagte hain.",
  "Spicy kick hai start mein.",
  "Aquatic feel hai, samundar jaisa.",
  "Earthy notes bhot grounding hain.",
  "Sweet perfumes pasand karne walon ke liye best hai.",
  "Dark aur mysterious scent hai.",
  "Light aur airy khushbu hai.",
  "Interview pe laga ke gaya tha, confidence mila.",
  "Date night ke liye perfect.",
  "Wedding season ke liye best choice.",
  "Eid par lagane ke liye liya hai.",
  "Ramazan offer mein liya tha, faida ho gaya.",
  "Sale ka wait kar raha hoon dubara.",
  "Bundle offer bhot achi thi.",
  "Value pack nikaalein please.",
  "Subscription model hona chahiye.",
  "Loyalty points milne chahiye.",
  "Referral discount diya karein.",
  "Website bhot easy to use hai.",
  "Order process smooth tha.",
  "Tracking details time pe mili.",
  "Packaging secure thi, bubble wrap acha tha.",
  "Box ke andar card bhot pyara tha.",
  "Personalized note ne dil jeet liya.",
  "Choti choti details pe dehan diya hai.",
  "Local brand ko support karna chahiye.",
  "Proudly Made in Pakistan.",
  "International brands se kam nahi.",
  "Export quality lagti hai.",
  "Dost ne pucha kahan se liya.",
  "Colleagues tareef kar rahe thay.",
  "Boss ne bhi notice kiya.",
  "Stranger ne rok kar pucha konsa perfume hai.",
  "Compliment getter hai yeh.",
  "Head turner fragrance.",
  "Mass appealing scent.",
  "Unique hai, aam nahi milti aisi khushbu.",
  "Nostalgic feel hai is mein.",
  "Bachpan ki yaad aa gayi.",
  "Pehli barish jaisi khushbu.",
  "Subah ki taazgi jaisa.",
  "Phoolon ke bagh jaisa.",
  "Jangal ki sair jaisa.",
  "Samundar ki hawa jaisa.",
  "Coffee date ke liye acha hai.",
  "Movie night ke liye theek hai.",
  "Grocery karte waqt bhi laga leta hoon.",
  "Sone se pehle lagata hoon, neend achi aati hai.",
  "Pillow mist ke taur pe use kiya, maza aa gaya.",
  "Room spray ke liye bhi acha hai.",
  "Car freshner se behtar hai.",
  "Wardrobe mein spray kiya, kapre mehak gaye.",
  "Dupatte pe lagaya, 3 din tak khushbu rahi.",
  "Coat pe lagaya tha, dry clean ke baad bhi smell hai.",
  "Jacket se khushbu nahi ja rahi, zabardast.",
  "Watch strap pe lagaya, ab haath se khushbu aati hai.",
  "Baalon mein lagaya, fresh feel hua.",
  "Beard oil ke sath mix kiya, acha combo bana.",
  "Lotion ke sath layer kiya, lasting barh gayi.",
  "Doosre perfume ke sath mix kiya, nayi khushbu ban gayi.",
  "Layering ke liye acha hai.",
  "Strong hai, sirf 2 spray kafi hain.",
  "Halka hai, 5-6 spray lagane parte hain.",
  "Atomizer bhot smooth mist banata hai.",
  "Bottle heavy aur premium feel deti hai.",
  "Cap magnetic hoti to aur acha hota.",
  "Label design bhot minimalist hai, pasand aaya.",
  "Color of juice is beautiful.",
  "Stain nahi chorta kapron par.",
  "Safed kapron pe bhi laga sakte hain.",
  "Black dress ke sath perfect match.",
  "White shirt aur yeh perfume, classic combo.",
  "Shalwar kameez ke sath desi vibes.",
  "Suit ke sath formal vibes.",
  "Kurta pajama ke sath acha lagta hai.",
  "Jeans t-shirt ke sath casual feel.",
  "Gym wear ke sath sporty feel.",
  "Jogging karte waqt lagaya, pasina badboo nahi bana.",
  "Garmi mein fresh rakhta hai.",
  "Sardi mein warm feel deta hai.",
  "Barish mein aur nikhar ke aati hai khushbu.",
  "Hawa chalti hai to khushbu phailti hai.",
  "Kamre mein ghustay hi pata chal jata hai.",
  "Lift mein khushbu reh gayi thi.",
  "Gaari mein chore diya tha, kharab nahi hua.",
  "Purse mein leak nahi hua.",
  "Travel mein le jana asaan hai.",
  "Gift wrap kar ke bheja, shukriya.",
  "Birthday note bhi likh diya tha, thanks.",
  "Anniversary gift tha, wife khush ho gayi.",
  "Valentine's day ke liye best gift.",
  "Eid gift ke liye order karunga.",
  "Ramzan mein ittar ki jagah yeh use kiya.",
  "Jumma ki namaz ke liye lagaya.",
  "Mehfil mein alag pehchan ban gayi.",
  "Shadi mein sab puch rahe thay.",
  "Reception ke liye perfect.",
  "Valima look complete ho gayi.",
  "Mehndi function mein dance karte hue khushbu aa rahi thi.",
  "Qawwali night ke liye best.",
  "Sufi vibes aati hain.",
  "Roohani khushbu hai.",
  "Dil ko sukoon milta hai.",
  "Mind relax ho jata hai.",
  "Stress kam karne ke liye acha hai.",
  "Aroma therapy jaisa feel hai.",
  "Bacho ko bhi pasand aaya.",
  "School teacher ne pucha konsa scent hai.",
  "Principal sahab ne tareef ki.",
  "Office boy bhi impress tha.",
  "Client meeting mein acha impression para.",
  "Sales job ke liye zaroori hai.",
  "Doctor hoon, patients ko bura nahi lagta.",
  "Banker hoon, full day fresh rehta hoon.",
  "Student budget ke hisaab se best hai.",
  "Pocket money se liya tha, worth it.",
  "Sale pe liya tha, sasta para.",
  "BOGO offer mein maza aa gaya.",
  "Tester bhot chota tha, thora bara karein.",
  "Samples khareedne ki option honi chahiye.",
  "Discovery set bhot acha idea hai.",
  "Har mahine naya try karta hoon.",
  "Nayab Scents ka fan ho gaya hoon.",
  "Ab international brands nahi leta.",
  "Local industry ko support kar ke khushi hui.",
  "Made in Pakistan pe fakhar hai.",
  "Quality control bhot acha hai.",
  "Batch to batch variation kam hai.",
  "Expiry date bhot dur ki thi.",
  "Ingredients natural lagte hain.",
  "Synthetic smell nahi hai.",
  "Luxury brand jaisi finishing hai.",
  "Cap ka weight acha hai.",
  "Box throw karne ka dil nahi karta.",
  "Shelf pe rakha hua acha lagta hai.",
  "Vanity ki shaan barha di.",
  "Instagram story pe lagaya, sab ne pucha.",
  "TikTok pe review dekh kar liya tha.",
  "YouTuber ki recommendation thi, sahi nikli.",
  "Facebook ad dekh kar order kiya.",
  "WhatsApp pe status lagaya tha.",
  "Friends ko bhi recommend kiya hai.",
  "Family mein sab ko gift karunga.",
  "Colleague ki shadi pe gift diya.",
  "Boss ko gift diya, promotion mil gayi (mazaq).",
  "Girlfriend ko diya, wo khush ho gayi.",
  "Boyfriend ko diya, usay pasand aaya.",
  "Mian biwi ke liye best combo deal hai.",
  "Behan bhai bhi share karte hain.",
  "Hostel life mein best companion hai.",
  "Travel bag ka must-have item.",
  "Emergency ke liye bag mein rakhta hoon.",
  "Last minute plan ke liye perfect.",
  "Meeting se pehle spray karein, confidence boost.",
  "Interview mein acha impression.",
  "Date pe jane se pehle zaroori hai.",
  "Gym bag mein hamesha rehta hai.",
  "Car ke dashboard mein fit ho jata hai.",
  "Office drawer mein rakha hai.",
  "Pocket size bhi nikalein please.",
  "Solid perfume bhi try karna chahunga.",
  "Attar oil bhi launch karein.",
  "Candles bhi banayein is khushbu ki.",
  "Body wash bhi hona chahiye is range ka.",
  "Shampoo mein bhi yehi khushbu ho to maza aa jaye.",
  "Beard oil bhi same scent ka ho.",
  "Hair mist bhi launch karein.",
  "Fabric spray bhi acha idea hai.",
  "Car diffuser bhi banayein.",
  "Reed diffusers bhi hone chahiye.",
  "Bakhoor bhi try karein.",
  "Oud chips bhi sell karein.",
  "Burner bhi available karein.",
  "Gift sets mein variety layein.",
  "Customized engraving ki option dein.",
  "Name likhwaya tha bottle pe, bhot acha laga.",
  "Gift card bhi hona chahiye.",
  "E-gift voucher ka option dein.",
  "International shipping shuru karein.",
  "Dubai mein delivery chahiye.",
  "UK mein friends mangwa rahe hain.",
  "USA mein shipping kab shuru hogi?",
  "Saudi Arabia mein demand hai.",
  "Canada mein bhi deliver karein.",
  "Australia mein bhi fans hain.",
  "Europe mein bhi bhejein.",
  "China mein bhi export karein.",
  "Duniya bhar mein naam roshan karein.",
  "Pakistani brand ko global banayein.",
  "Best wishes for future.",
  "Keep up the good work.",
  "Allah barkat de.",
  "MashaAllah bhot acha kaam hai.",
  "JazakAllah for amazing product.",
  "SubhanAllah kya khushbu hai.",
  "Alhamdulillah satisfied customer.",
  "InshaAllah dubara order karunga.",
  "Allah kamiyab kare."
];

// Helper to generate 30 reviews per product ID
export const getReviewsForProduct = (productId: number): Review[] => {
  const reviews: Review[] = [];
  
  for (let i = 0; i < 30; i++) {
    // Generate distinct but deterministic data based on productId
    reviews.push({
      id: `review-${productId}-${i}`,
      name: NAMES[(i + productId * 3) % NAMES.length], // Randomize name index
      rating: 4 + (i % 2 === 0 ? 1 : 0.5), // Mostly 4.5 or 5 stars
      comment: COMMENTS[(i + productId) % COMMENTS.length],
      date: `${Math.floor(Math.random() * 28) + 1} Jan, 2026`
    });
  }
  return reviews;
};